name: implement pytest with github action in python project

on: [push, workflow_dispatch]
env:
  GLOBAL_TEST_VARIABLE: ${{ secrets.TEST_SECRET }}
jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.outputid.outputs.email }}
    steps:
      - name: output event data
        run: echo "${{ toJSON(github.event_name) }}"
      - name: Get the code
        uses: actions/checkout@v4
      - name: show secret test
        run: echo "test secret ${{ env.GLOBAL_TEST_VARIABLE }}"
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: test the code
        run: pytest -s -v
      - name: showcase output
        id: outputid
        run: echo "email=sahulinkan7@gmil.com" >> $GITHUB_OUTPUT
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ouput_files
          path: logs
  outputjob:
    runs-on: ubuntu-latest
    needs: checkout_and_test
    steps:
      - name: get previous job output
        run: echo "output from previous job ${{needs.checkout_and_test.outputs.output1}}"
  download_artifact_job:
    runs-on: ubuntu-latest
    needs: outputjob
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ouput_files
      - name: downloaded files
        run: ls
      - name: read logs
        run: cat pytestlogs.log